# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/86188/Desktop/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test.xdc

# Block Designs: bd/project/project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project || ORIG_REF_NAME==project} -quiet] -quiet

# IP: bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_processing_system7_0_0 || ORIG_REF_NAME==project_processing_system7_0_0} -quiet] -quiet

# XDC: bd/project/project_ooc.xdc
