# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/86188/Desktop/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test.srcs/sources_1/bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xci
# IP: The module: 'project_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86188/Desktop/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test.srcs/sources_1/bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/86188/Desktop/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test.srcs/sources_1/bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xci
# IP: The module: 'project_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86188/Desktop/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test/XC7Z045_BTandSD_Test.srcs/sources_1/bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
